Проверять Square
MasalovaNIX/Automation pull request #1
Opened 2021-05-17 15:48 UTC by MasalovaNIX

2021-05-20 10:21 UTC, Zetmask requested changes

2021-05-20 10:21 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/Coordinates.java
> +    public static int[] arrayX(int points) { // тут мне подсказали сделать массив с параметром, но зато теперь я знаю
такие штуки лучше называть более понятным именем. Например, generateCoordinateXArray - но я думаю, что можно обойтись и без этого класса вообще

2021-05-20 10:21 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/Main.java
> +            sortedArea.put(list[9].getCountedArea(), list[9].getName());
это исправим чуть позже, когда разберёмся с остальным

2021-05-20 10:21 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Circle.java
> +        this.arrayY = Coordinates.arrayY(2);
Получается, ты хардкодишь все значения внутри конкретной фигуры. Давай попробуем сделать более красиво
public Circle(String name, int[] x, int[] y) {
     super(name, x, y);
}

То есть, при создании фигуры ты передаешь в параметрах имя и массив координат x, y

2021-05-20 10:21 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Circle.java
> +        return this.name+ " Coordinates X: " + Arrays.toString(this.arrayX) + " Coordinates Y: "+Arrays.toString(this.arrayY) + " Area " + countedArea();
Если честно, вообще не понял, зачем этот метод? Да и называть его toString() - не лучший вариант, так как такое название уже есть в джаве

2021-05-20 10:21 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Figures.java
> +    public Figures() {
Так как мы убираем тот хардкод из других фигур, то здесь нам нужен абстрактный конструктор

public Figures(String name, int[] x, int[] y) {
     this.name = name;
     this.coordinateX = x;
     this.coordinateY = y;
   }

2021-05-20 10:21 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Figures.java
> +        Figures.name = name;
this.name = name;

2021-05-20 10:21 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Figures.java
> +    private static double countedArea;
все эти штуки должны быть private, а доступ к ним получаем через set/get

2021-05-20 10:21 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Circle.java
> +    double countArea;
ты их объявила, но нигде не используешь

2021-05-20 10:51 UTC, MasalovaNIX commented on src/main/java/com/autoSchoolPartThreeAndSix/Coordinates.java
> +    public static int[] arrayX(int points) { // тут мне подсказали сделать массив с параметром, но зато теперь я знаю
в процессе бесед вроде решили вынести в отдельный класс координаты

2021-05-20 10:53 UTC, MasalovaNIX commented on src/main/java/com/autoSchoolPartThreeAndSix/Main.java
> +            sortedArea.put(list[9].getCountedArea(), list[9].getName());
тут в столбик) ну потому что не работало никак - так наглядно видно, что делаю

2021-05-20 15:40 UTC, Zetmask requested changes

2021-05-20 15:40 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Circle.java
> +            this.area = getArea();
тут этого не надо делать. Что, например, если я хочу создать фигуру, но не высчитывать её площадь?

2021-05-20 15:40 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Circle.java
> +    public double getArea(){
имя метода не соответствует тому, что он делает. evaluateArea или countArea будет лучше

2021-05-20 15:40 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Figures.java
> +//    public static String getName() {
setName и getName должны быть. Хоть имя ты и создаешь в main явно ("Square"), но getName пригодится, когда будем сортировать фигуры по площади

2021-05-20 15:40 UTC, Zetmask commented on src/main/java/com/autoSchoolPartThreeAndSix/figure/Circle.java
> +        return Math.round(Math.PI *((Math.pow((arrayX[0] - arrayX[1]), 2) + (Math.pow(arrayY[0] - arrayY[1], 2)))));
Так как уберём thsi.area = getArea(), то метод перестанет работать. Лучше поменять, чтобы он принимал координаты как параметры
getArea(int[] x, int[] y) {}

2021-05-21 12:47 UTC, Zetmask approved these changes

2021-05-21 13:24 UTC, merged